spring:
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  thymeleaf:
    cache: false
  jpa:
    database: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  mail:
    host:
#logging:
#  level:
#    root: info
#    com.cafe24.springmvcstudy : debug

mail:
  name: eunhyuk
  host:
    ip: 127.0.0.1
    port: 8080